# Generated by Django 4.1 on 2024-02-22 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'USER', 'verbose_name_plural': 'USERS'},
        ),
    ]
